### ISSUE TITLE
version 7.1.0 and 7.1.1 hang on Linux Mint 22 (7.0.0 is fine)

### ISSUE THREAD

**Issue by arxo** [Yubico/yubioath-flutter#1729]
Since version 7.1.0 I of Yubico Authenticator I experience reproducible hangs.
The UI freezes and I cannot enter the OTP or FIDO pin:
![image](https://github.com/user-attachments/assets/63032b05-0671-4093-a847-5e52dfb4b1f9)

Here is the gzipped strace output for versions 7.0.0 (works fine) / 7.1.0 (hangs) / 7.1.1 (hangs) for comparison:
[strace_7.0.0.txt.gz](https://github.com/user-attachments/files/17756399/strace_7.0.0.txt.gz)
[strace_7.1.0.txt.gz](https://github.com/user-attachments/files/17756400/strace_7.1.0.txt.gz)
[strace_7.1.1.txt.gz](https://github.com/user-attachments/files/17756401/strace_7.1.1.txt.gz)

YubiKey model: YubiKey 5 NFC
OS: Linux Mint 22
CPU: Ryzen 7 3700X
Mainboard: MSI B-550A Pro
GPU: NVidia GeForce GTX 1050 Ti

**Comment by AdamVe** [comment]
Hi, thank you for providing the logs. I’ve reviewed them and noticed that the 7.1.x versions stop responding after a specific system call, but I’m unable to pinpoint the exact cause at the moment. 🙂

Could you please run the program with the following arguments to capture all the app's log messages?

```
./authenticator --log-level traffic --log-file authenticator.log
```

Additionally, I’ve looked into whether this might be a known issue within our framework, Flutter, and I found a similar case (see https://github.com/flutter/flutter/issues/153560). In that case, the app freezes when a text field is activated, and it can remain unresponsive for up to 40 seconds. Could you check if you’re experiencing something similar on your end?

**Comment by arxo** [comment]
@AdamVe 
Is it safe to provide the traffic logging as long I just open the app and do not enter a pin (which I can't anyway because of the bug)?
I do not want to publicly expose any sensitive data.

**Comment by arxo** [comment]
Btw. I can reproduce the Flutter issue you linked (https://github.com/flutter/flutter/issues/153560) on my machine as well.

**Comment by AdamVe** [comment]
Certainly! Here’s a rephrased version of your message:

Thank you for following up. I understand your concerns. Opening the app without entering your PIN or password should not reveal any sensitive information in the log. You can review the log before sharing it. It will include JSON communication, RECV and SEND hex data, and the YubiKey DeviceInfo—feel free to remove or obfuscate any sensitive details as needed.

I see that you were able to reproduce the Flutter issue. In this case, I believe we’ll need to wait for a bug fix from Flutter. Personally, I wasn’t able to reproduce the issue on my end.

**Comment by arxo** [comment]
Since Flutter is likely the culprit, I think I won't bother with the log for now and wait for the upstream fix.
Btw. I tried this on three other PCs running LM 22 and they do not have the issue (all Intel CPUs with integrated graphics).

**Comment by AdamVe** [comment]
Am I right that you see the issue on a machine with Nvidia drivers? Is there any chance you could try to run the app without the driver loaded and see if that changes anything?

**Comment by arxo** [comment]
Bingo :) After booting a LM 22 live image from USB, which uses the nouveau driver instead of NVidia's, I could run 7.1.x without any hangs in the pin input fields.

**Comment by arxo** [comment]
In the flutter bug ticket someone reproduce this with AMD graphics (and NVidia was fine, but no mention of which driver was used), so it's not necessarily just an NVidia issue.

**Comment by AdamVe** [comment]
I agree. Let's keep this ticket opened till we have a version without the buggy behavior. Thanks for reporting and taking your time with preparing the logs and testing :)

**Comment by arxo** [comment]
FYI, there is now a potential workaround mentioned in the flutter ticket: disabling the virtual keyboard in Linux Mint's accessibility options.
I successfully tested this.
Note that this is different than just closing the virtual keyboard - it has to be fully disabled. Opening the virtual keyboard app from the start menu afterwards will re-enable it.

**Comment by Crux-0x16** [comment]
Hi, i have the same problem on my PC with AMD CPU , AMD GPU and Linux Mint DB 6. The problem is on every USB port on the AMD PC. 

It started after I switched from version 5 to 7. The key is working normal on other Intel CPU and GPU tablets with Linux Mint or POP OS. 

PS: I can enter the pin. All i have to to do is waiting in the the Authenticator window for a minute or so.

**Comment by KobeW50** [comment]
I also have this issue on my laptop with no dedicated GPU. It only has Intel's integrated graphics (Intel Iris Xe).

<details>
<summary><strong>Output of 'inxi -Gxxx'</strong></summary>
<br>

```
Graphics:
  Device-1: Intel Alder Lake-P GT2 [Iris Xe Graphics] vendor: Hewlett-Packard
    driver: i915 v: kernel arch: Gen-12.2 ports: active: HDMI-A-1,eDP-1
    empty: DP-1,DP-2 bus-ID: 00:02.0 chip-ID: 8086:46a6 class-ID: 0300
  Device-2: Chicony HP True Vision 5MP Camera driver: uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 bus-ID: 3-9:6 chip-ID: 04f2:b765
    class-ID: fe01 serial: 0001
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 4800x1800 s-dpi: 96 s-size: 1270x476mm (50.00x18.74")
    s-diag: 1356mm (53.4")
  Monitor-1: HDMI-A-1 mapped: HDMI-1 pos: right model: Dell S2340L
    serial: DGPV446B0MDT res: 1920x1080 hz: 60 dpi: 96
    size: 509x286mm (20.04x11.26") diag: 584mm (23") modes: max: 1920x1080
    min: 720x400
  Monitor-2: eDP-1 pos: primary,left model: Samsung 0x4170 res: 2880x1800
    dpi: 242 size: 302x189mm (11.89x7.44") diag: 356mm (14") modes: 2880x1800
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris
    device: 1 drv: swrast gbm: drv: iris surfaceless: drv: iris x11: drv: iris
    inactive: wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa
    v: 25.0.7-0ubuntu0.24.04.2 glx-v: 1.4 direct-render: yes renderer: Mesa
    Intel Iris Xe Graphics (ADL GT2) device-ID: 8086:46a6
```
</details>
